<?php

// Include DatabaseHelper.php file
require_once ('DBSHelper.php');

// Instantiate DatabaseHelper class
$database = new DBSHelper();

?>

<html>
<head>
<title>My Project</title>
<link rel="stylesheet" href="style.css">
</head>

<body>
	<br>
	<h1>My First PHP Project</h1>

	<!-- Add Person -->
	<div class="card">
		<ol class="=ol">
			<h2>Add Rental Office:</h2>
			<form method="post" action="addRentalOffice.php">
				<!-- Person ID is not needed, because its autogenerated by the database -->

				<!-- Name textbox -->
				<div>
					<label for="new_address">Address:</label> <input id="new_address"
						name="address" type="text" maxlength="300">
				</div>
				<br>

				<!-- Surname textbox -->
				<div>
					<label for="new_office_name">Office Name:</label> <input
						id="new_office_name" name="office_name" type="text"
						maxlength="200">
				</div>
				<br>

				<!-- Submit button -->
				<div>
					<button type="submit">Add Rental Office</button>
				</div>
			</form>
		</ol>
	</div>

	<br>
	<hr>


	<div class="card">
		<ol class="=ol">
			<h2>Delete Rental Office:</h2>
			<form method="post" action="deleteRentalOffice.php">
				<div>
					<label for="del_address">Address:</label> <input id="del_address"
						name="address" type="text" maxlength="300">
				</div>
				<br>

				<div>
					<button type="submit">Delete Rental Office</button>
				</div>
			</form>
		</ol>
	</div>


	<br>
	<hr>

	<div class="card">
		<ol class="=ol">
			<h2>Update Rental Office Name:</h2>
			<form method="post" action="updateRentalOffice.php">
				<div>
					<label for="address">Address:</label> <input id="address"
						name="address" type="text" maxlength="300">
				</div>
				<br>
				<div>
					<label for="new_office_name">New Office Name:</label> <input
						id="new_office_name" name="office_name" type="text"
						maxlength="200">
				</div>
				<br>
				<div>
					<button type="submit">Update Office Name</button>
				</div>
			</form>
		</ol>
	</div>

	<br>
	<hr>

	<div class="card">
		<ol class="=ol">
			<h2>Show Rental Offices:</h2>
			<form method="post" action="readRentalOffice.php">
				<button type="submit">Show Rental Offices</button>
			</form>
		</ol>
	</div>


	<br>
	<hr>


	<div class="card">
		<ol class="=ol">
			<h2>Add Customer:</h2>
			<form method="post" action="addCustomer.php">
				<div>
					<label for="new_driving_license_number">Driving License Number:</label>
					<input id="new_driving_license_number"
						name="driving_license_number" type="text" maxlength="300">
				</div>
				<br>
				<div>
					<label for="new_c_name">Customer's Name:</label> <input id="c_name"
						name="c_name" type="text" maxlength="200">
				</div>
				<br>
				<div>
					<label for="new_contact_info">Telephone or eMail:</label> <input
						id="new_contact_info" name="contact_info" type="text"
						maxlength="300">
				</div>
				<br>

				<div>
					<label for="reantal_id">Rental Id:</label> <input id="rental_id"
						name="rental_id" type="text" maxlength="300">
				</div>
				<br>
				<div>
					<button type="submit">Add Rental Office</button>
				</div>
			</form>
		</ol>
	</div>

	<br>
	<hr>

	<div class="card">
		<ol class="=ol">
			<h2>Delete Customer:</h2>
			<form method="post" action="deleteCustomer.php">
				<div>
					<label for="del_license">Driving License Number:</label> <input
						id="del_license" name="driving_license_number" type="text"
						maxlength="300">
				</div>
				<br>

				<div>
					<button type="submit">Delete Customer</button>
				</div>
			</form>
		</ol>
	</div>

	<br>
	<hr>

	<div class="card">
		<ol class="=ol">
			<h2>Update Customer Info:</h2>
			<form method="post" action="updateCustomer.php">
				<div>
					<label for="driving_license_number">Driving License Number:</label>
					<input id="driving_license_number" name="driving_license_number"
						type="text" maxlength="300">
				</div>
				<br>
				<div>
					<label for="new_contact_info">New Contact Info:</label> <input
						id="contact_info" name="contact_info" type="text" maxlength="200">
				</div>
				<br>
				<div>
					<button type="submit">Update Contact Info</button>
				</div>
			</form>
		</ol>
	</div>

	<br>
	<hr>

	<div class="card">
		<ol class="=ol">
			<h2>Show Customers:</h2>
			<form method="post" action="readCustomer.php">
				<button type="submit">Show Customers</button>
			</form>
		</ol>
	</div>

	<br>
	<hr>

	<div class="card">
		<ol class="=ol">
			<h2>Show Number of Customers in Office:</h2>
			<form method="post" action="showCustomersInOffice.php">
				<label for="rental_id">Rental ID:</label> <input id="rental_id"
					name="rental_id" type="text" maxlength="300">
				<button type="submit">Show Customers</button>
			</form>
		</ol>
	</div>
</body>
</html>
